# List of API keys

ALPACA_API_KEY = "PKNFCKXJFWSS2NO9PAT0"
ALPACA_SECRET_KEY = "5kCk93UMFANfO4UNY12gSGaS8ROoX2KuulHo0DDe"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"
ALPHA_VANTAGE_KEY = "WFGPUZ5MTM4VZ6H3"